# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    # - name: Run a one-line script
    #   run: diff bandit1/bandit1.out bandit2/bandit2.out

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        pip3 install paramiko
        for i in {0..5}; do python3 bandit$i/bandit$i.py | tee bandit$i/bandit$i.out1; done
        echo "Start diff command"
        for i in {0..5}; do echo $i; diff bandit$i/bandit$i.out1 bandit$i/bandit$i.out; echo -e "\n\n\n"; done
        echo "End diff command"
        for i in {0..5}; do rm bandit$i/bandit$i.out1; done
